In [ ]:

from google.colab import files

uploaded = files.upload()

Saving Example1.txt to Example1.txt
Saving Example2.txt to Example2.txt
Saving file1.csv to file1.csv
Saving file1.xlsx to file1.xlsx

In [ ]:
file1 = open("Example1.txt", "w")

file1.write("This is line 1")
file1.close()

print("File created successfully")

File created successfully

In [ ]:
file1 = open("Example1.txt", "r")

print(file1.name)
print(file1.mode)

file1.close()

Example1.txt
r

In [ ]:
with open("Example1.txt", "r") as file1:
    file_stuff = file1.read()

print(file_stuff)

This is line 1

In [ ]:
with open("Example1.txt", "r") as file1:
    file_stuff = file1.read()

print(file1.closed)
print(file_stuff)

True
This is line 1

In [ ]:
with open("Example1.txt", "w") as file1:
    file1.write("This is line 1\n")
    file1.write("This is line 2\n")
    file1.write("This is line 3\n")

In [ ]:
with open("Example1.txt", "r") as file1:
    file_stuff = file1.readlines()

print(file_stuff)

['This is line 1\n', 'This is line 2\n', 'This is line 3\n']

In [ ]:
with open("Example1.txt", "r") as file1:
    file_stuff = file1.readline()

print(file_stuff)

This is line 1

In [ ]:
with open("Example1.txt", "r") as file1:
    print(file1.readline())
    print(file1.readline())

This is line 1

This is line 2

In [ ]:
with open("Example1.txt", "r") as file1:
    data = file1.read(10)

print(data)

This is li

In [ ]:
with open("Example2.txt", "w") as file1:
    file1.write("This is line A")

print("Data written successfully")

Data written successfully

In [ ]:
with open("Example2.txt", "w") as file1:
    file1.write("This is line A\n")
    file1.write("This is line B\n")

print("Data written successfully")

Data written successfully

In [ ]:
with open("Example2.txt", "r") as file1:
    print(file1.read())

This is line A
This is line B

In [ ]:
lines = [
    "This is line A\n",
    "This is line B\n",
    "This is line C\n"
]

with open("Example2.txt", "w") as file1:
    for line in lines:
        file1.write(line)

print("Lines written successfully")

Lines written successfully

In [ ]:
with open("Example2.txt", "a") as file1:
    file1.write("This is line D\n")

In [ ]:
with open("Example2.txt", "r") as file1:
    print(file1.read())

This is line A
This is line B
This is line C
This is line D

In [ ]:
with open("Example2.txt", "r") as readfile:
    lines = readfile.readlines()

with open("Example3.txt", "w") as writefile:
    for line in lines:
        writefile.write(line)

print("File copied successfully")

File copied successfully

In [ ]:
import pandas as pd

In [ ]:
data = """Artist,Album,Released,Rating
Michael Jackson,Thriller,1982,10
AC/DC,Back in Black,1980,9.5
Pink Floyd,The Dark Side of the Moon,1973,9
Whitney Houston,The Bodyguard,1992,8.5
Meat Loaf,Bat Out of Hell,1977,8
"""

with open("file1.csv", "w") as file:
    file.write(data)

print("CSV file created")

CSV file created

In [ ]:
import pandas as pd

df = pd.read_csv("file1.csv")

print(df)

            Artist                      Album  Released  Rating
0  Michael Jackson                   Thriller      1982    10.0
1            AC/DC              Back in Black      1980     9.5
2       Pink Floyd  The Dark Side of the Moon      1973     9.0
3  Whitney Houston              The Bodyguard      1992     8.5
4        Meat Loaf            Bat Out of Hell      1977     8.0

In [ ]:
df.head()

            Artist                      Album  Released  Rating
0  Michael Jackson                   Thriller      1982    10.0
1            AC/DC              Back in Black      1980     9.5
2       Pink Floyd  The Dark Side of the Moon      1973     9.0
3  Whitney Houston              The Bodyguard      1992     8.5
4        Meat Loaf            Bat Out of Hell      1977     8.0

In [ ]:
df.head(3)

            Artist                      Album  Released  Rating
0  Michael Jackson                   Thriller      1982    10.0
1            AC/DC              Back in Black      1980     9.5
2       Pink Floyd  The Dark Side of the Moon      1973     9.0

In [ ]:
df = pd.read_excel("file1.xlsx")

df.head()

            Artist                      Album  Released  Rating
0  Michael Jackson                   Thriller      1982    10.0
1            AC/DC              Back in Black      1980     9.5
2       Pink Floyd  The Dark Side of the Moon      1973     9.0
3  Whitney Houston              The Bodyguard      1992     8.5
4        Meat Loaf            Bat Out of Hell      1977     8.0

In [ ]:
songs = {
    "Album": [
        "Thriller",
        "Back in Black",
        "The Dark Side of the Moon",
        "The Bodyguard",
        "Bat Out of Hell"
    ],

    "Released": [1982, 1980, 1973, 1992, 1977],

    "Length": [
        "00:42:19",
        "00:42:11",
        "00:42:49",
        "00:57:44",
        "00:46:33"
    ]
}

songs_frame = pd.DataFrame(songs)

print(songs_frame)

                       Album  Released    Length
0                   Thriller      1982  00:42:19
1              Back in Black      1980  00:42:11
2  The Dark Side of the Moon      1973  00:42:49
3              The Bodyguard      1992  00:57:44
4            Bat Out of Hell      1977  00:46:33

In [ ]:
songs_frame

                       Album  Released    Length
0                   Thriller      1982  00:42:19
1              Back in Black      1980  00:42:11
2  The Dark Side of the Moon      1973  00:42:49
3              The Bodyguard      1992  00:57:44
4            Bat Out of Hell      1977  00:46:33

In [ ]:
df["Artist"]

0    Michael Jackson
1              AC/DC
2         Pink Floyd
3    Whitney Houston
4          Meat Loaf
Name: Artist, dtype: object

In [ ]:
print(df.iloc[0, 0])

Michael Jackson

In [ ]:
print(df.iloc[1, 0])

AC/DC

In [ ]:
print(df.iloc[0, 2])

1982

In [ ]:
print(df.iloc[1, 2])

1980

In [ ]:
df.iloc[0:2]

            Artist          Album  Released  Rating
0  Michael Jackson       Thriller      1982    10.0
1            AC/DC  Back in Black      1980     9.5

In [ ]:
z = df.iloc[0:2, 0:3]

print(z)

            Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

In [ ]:
df.iloc[[0, 2, 4]]

            Artist                      Album  Released  Rating
0  Michael Jackson                   Thriller      1982    10.0
2       Pink Floyd  The Dark Side of the Moon      1973     9.0
4        Meat Loaf            Bat Out of Hell      1977     8.0

In [ ]:
df[["Artist", "Album"]]

            Artist                      Album
0  Michael Jackson                   Thriller
1            AC/DC              Back in Black
2       Pink Floyd  The Dark Side of the Moon
3  Whitney Houston              The Bodyguard
4        Meat Loaf            Bat Out of Hell

In [ ]:
df["Released"].unique()

array([1982, 1980, 1973, 1992, 1977])

In [ ]:
df["Artist"].unique()

array(['Michael Jackson', 'AC/DC', 'Pink Floyd', 'Whitney Houston',
       'Meat Loaf'], dtype=object)

In [ ]:
df[df["Released"] >= 1980]

            Artist          Album  Released  Rating
0  Michael Jackson       Thriller      1982    10.0
1            AC/DC  Back in Black      1980     9.5
3  Whitney Houston  The Bodyguard      1992     8.5

In [ ]:
df[df["Released"] < 1980]

       Artist                      Album  Released  Rating
2  Pink Floyd  The Dark Side of the Moon      1973     9.0
4   Meat Loaf            Bat Out of Hell      1977     8.0

In [45]:
df[df["Rating"] > 8]

            Artist                      Album  Released  Rating
0  Michael Jackson                   Thriller      1982    10.0
1            AC/DC              Back in Black      1980     9.5
2       Pink Floyd  The Dark Side of the Moon      1973     9.0
3  Whitney Houston              The Bodyguard      1992     8.5

In [46]:
df.to_csv("new_songs.csv", index=False)

print("CSV file saved successfully")

CSV file saved successfully

In [47]:
new_df = pd.read_csv("new_songs.csv")

new_df.head()

            Artist                      Album  Released  Rating
0  Michael Jackson                   Thriller      1982    10.0
1            AC/DC              Back in Black      1980     9.5
2       Pink Floyd  The Dark Side of the Moon      1973     9.0
3  Whitney Houston              The Bodyguard      1992     8.5
4        Meat Loaf            Bat Out of Hell      1977     8.0